### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by LucasSilvaFerreira** [phageghost/python-genome-browser#2]
Hi, Should it be a commentary ?

File "/Users/lxf453/miniconda2/lib/python2.7/site-packages/pygbrowse/datasources.py", line 53
    result: pandas.Series = self._query(query_chrom=query_chrom, query_start=query_start, query_end=query_end)
          ^
SyntaxError: invalid syntax

**Comment by LucasSilvaFerreira** [comment]
Hi, after comment that piece of code I found this issue.
 File "pygbrowse/plots.py", line 426
    def _load_gene_models(self, gff3_filename, chromosome_name_converter, *, sources, gene_types,
                                                                           ^
SyntaxError: invalid syntax


I will wait for the fixes. I'm very interested in use this package. 
I writing some papers right now and it will be very nice cite your tool.
Thank you

**Comment by phageghost** [comment]
Hi Lucas,

The first issue you noted is an instance of [Type Hinting](https://www.python.org/dev/peps/pep-0484/).

The second issue might be the presence of the '*' in the parameter list, used to denote non-positional keyword arguments.

Both of these syntax features should be supported by the most recent version of Python 3, but I have removed them in this case to improve backward compatibility since they are not functionally necessary.

**Comment by LucasSilvaFerreira** [comment]
Hi,
Does it makes sense!
I was using python 2.7 (That syntax is strange for me! I really thought was some typo)
I will try to run this again. Thank you for the help
Lucas

**Comment by phageghost** [comment]
Hi,

Yes, that would explain it. I haven't targeted python 2.7 in this project or tested it in that environment. Given the dwindling usage of 2.7 these days I doubt I will ever explicitly support it.

I just pushed a new version to PyPi that improves the speed and robustness of the GFF parsing (and also changes the interface slightly -- see the tutorial notebook for details). Please try it out and let me know what issues you encounter.

Thanks!
